

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

##Postgres
spring.application.name=COMPROJ
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ap6672@cck
spring.datasource.driver-class-name=org.postgresql.Driver

##Create table. Since it is only create whenver you start the d/b it will flush your d/b meaning there will be 0 records
##spring.jpa.hibernate.ddl-auto=create

##The database will not recreate even if reloaded since there is "none"
spring.jpa.hibernate.ddl-auto=update
## Whenver you are starting app it is creating an object and this call them through jpa driver,
## so to see the sql query behing the process we use sql =  true
spring.jpa.show-sql=true










